### ISSUE TITLE
Joystick input for sliders is not reported

### ISSUE THREAD

**Issue by MrMinimal** [Jonesey13/multiinput-rust#5]
Using a Thrustmaster Warthog Throttle which has a "Slider". It seems to be different from a normal axis because events are not reported, even though it moves in the Windows properties window:

![image](https://user-images.githubusercontent.com/8739690/40018030-622d607c-57bb-11e8-8ff7-e0550a8e3669.png)

Any idea why that would be happening? Would I have to implement that, if so can you give me a lead where to start?

Cheers

**Comment by Jonesey13** [comment]
Yeah I think I know what might need doing here (even though I can't test this myself). I've attempted to add support on the branch "slider_test". Let me know if it works and I'll merge it in!

**Comment by MrMinimal** [comment]
`slider_test` sure can be merged, works as expected now. You really are on fire today 😄 Thanks!
(also I love using Gitter for projects I am involved in)
