### ISSUE TITLE
Open Specific Keyboard or Mouse

### ISSUE THREAD

**Issue by patrickisgreene** [Jonesey13/multiinput-rust#6]
I know the whole point of this library is for getting multiple input devices at the same time but i would also find it useful to open one specific keyboard device. I think adding a 2 new variant to `DeviceType` would do the trick. maybe something like 
```
DeviceType::Keyboard(_, _),
DeviceType::Mouse(_,_),
```

I would like to implement this functionality, but i'm very new to windows programming (been programming in rust for 4 years now though) and not sure how to use the winapi. Could you shed a little light on implementing this for me?

**Comment by Jonesey13** [comment]
This has now been implemented as a filter_devices() method on the input manager struct (as far as I know the rawinput api does not support filtering out individual devices). Closing the ticket.
